name: documentation-ci
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
          pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          mkdocs build 

      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: site/

      - name: Push changes gh-pages
        run: mkdocs gh-deploy --force
